In [ ]:
from __future__ import annotations

import warnings

from ase.md.velocitydistribution import MaxwellBoltzmannDistribution
from pymatgen.core import Lattice, Structure
from pymatgen.io.ase import AseAtomsAdaptor
from ase.io import read
import pandas as pd

import matgl
matgl.set_backend("DGL")
from matgl.ext._ase_dgl import MolecularDynamics, PESCalculator, Relaxer

# To suppress warnings for clearer output
warnings.simplefilter("ignore")

pot = matgl.load_model("../pretrained_models/QET-MatQ-PES")

/global/cfs/projectdirs/m4555/Jun/conda_envs/matgl/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [15]:
atoms = read("./solvation_zn/zn_300_100.000ps.xyz")

calc = PESCalculator(pot)
# set up the calculator for atoms object
atoms.set_calculator(calc)
df = pd.DataFrame({"symbols": atoms.get_chemical_symbols(), "charges": atoms.get_charges()})
df.groupby(by=["symbols"]).mean()

          charges
symbols
H        0.383985
O       -0.797863
Zn       0.637711

In [16]:
atoms = read("../../GCQeq/dataset/poscars/POSCAR_0")

calc = PESCalculator(pot)
# set up the calculator for atoms object
atoms.set_calculator(calc)
df = pd.DataFrame({"symbols": atoms.get_chemical_symbols(), "charges": atoms.get_charges()})
df.groupby(by=["symbols"]).mean()

          charges
symbols
Mo       0.519817
S       -0.259908

In [17]:
atoms = read("../../GCQeq_md/mos2_solvent/charged/POSCAR")

calc = PESCalculator(pot)
# set up the calculator for atoms object
atoms.set_calculator(calc)
df = pd.DataFrame({"symbols": atoms.get_chemical_symbols(), "charges": atoms.get_charges()})
df.groupby(by=["symbols"]).mean()

          charges
symbols
H        0.402357
Mo       0.539204
O       -0.760995
S       -0.352939